# Generated by Django 4.2 on 2024-06-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricco_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='localidad',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barrio', to='ricco_app.localidad'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direccion', to='ricco_app.barrio'),
        ),
    ]
