# Generated by Django 4.2 on 2025-05-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricco_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cancelable_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cancelable_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
