# Generated by Django 4.2 on 2024-06-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricco_app', '0002_alter_barrio_localidad_alter_direccion_barrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='barrio',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direccion', to='ricco_app.barrio'),
        ),
    ]
