# Generated by Django 4.2 on 2025-05-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricco_app', '0002_compra_cancelable_hasta_compra_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
