# Generated by Django 4.2 on 2025-02-15 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricco_app', '0003_alter_customuser_username_alter_direccion_barrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barrio', to='ricco_app.localidad'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='ricco_app.direccion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='ricco_app.rol'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='ricco_app.compra'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='ricco_app.producto'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direccion', to='ricco_app.barrio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rol_permiso',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permiso', to='ricco_app.permiso'),
        ),
        migrations.AlterField(
            model_name='rol_permiso',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permiso', to='ricco_app.rol'),
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedido',
        ),
        migrations.AlterModelTable(
            name='permiso',
            table='permiso',
        ),
        migrations.AlterModelTable(
            name='rol_permiso',
            table='rol_permiso',
        ),
    ]
