# Generated by Django 4.2 on 2025-02-17 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricco_app', '0004_alter_barrio_localidad_alter_compra_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
    ]
