# Generated by Django 4.2 on 2025-03-04 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricco_app', '0006_compra_detalles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='detalles',
        ),
        migrations.AlterField(
            model_name='compra',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
