# Generated by Django 4.2 on 2025-04-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricco_app', '0007_remove_compra_detalles_alter_compra_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
