# Generated by Django 4.2 on 2025-04-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricco_app', '0008_producto_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imgUrl',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
