# Generated by Django 4.2 on 2025-04-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricco_app', '0009_producto_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imgUrl',
        ),
    ]
