# Generated by Django 5.1.5 on 2025-04-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricco_app', '0010_remove_producto_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='main_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
