# Generated by Django 4.2 on 2024-10-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricco_app', '0002_remove_customuser_username_customuser_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
